# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingFortigate.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingFortigateDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(254, 76)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_fortigate = QtWidgets.QHBoxLayout()
        self.layout_fortigate.setSpacing(0)
        self.layout_fortigate.setObjectName("layout_fortigate")
        self.label_fortigate = QtWidgets.QLabel(Dialog)
        self.label_fortigate.setObjectName("label_fortigate")
        self.layout_fortigate.addWidget(self.label_fortigate)
        self.lineEdit_fortigate = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_fortigate.setObjectName("lineEdit_fortigate")
        self.layout_fortigate.addWidget(self.lineEdit_fortigate)
        self.layout_fortigate.setStretch(0, 1)
        self.layout_fortigate.setStretch(1, 3)
        self.verticalLayout.addLayout(self.layout_fortigate)
        self.btn_submit = QtWidgets.QPushButton(Dialog)
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout.addWidget(self.btn_submit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_fortigate.setText(_translate("Dialog", "Fortigate:"))
        self.lineEdit_fortigate.setInputMask(_translate("Dialog", "000.000.000.000"))
        self.lineEdit_fortigate.setText(_translate("Dialog", "10.209.25.126"))
        self.btn_submit.setText(_translate("Dialog", "Submit"))
