# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingZabbix.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingZabbixDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(339, 116)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layout_siteID = QtWidgets.QHBoxLayout()
        self.layout_siteID.setSpacing(0)
        self.layout_siteID.setObjectName("layout_siteID")
        self.label_siteID = QtWidgets.QLabel(Dialog)
        self.label_siteID.setObjectName("label_siteID")
        self.layout_siteID.addWidget(self.label_siteID)
        self.lineEdit_siteID = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_siteID.setInputMask("")
        self.lineEdit_siteID.setText("")
        self.lineEdit_siteID.setMaxLength(5)
        self.lineEdit_siteID.setObjectName("lineEdit_siteID")
        self.layout_siteID.addWidget(self.lineEdit_siteID)
        self.layout_siteID.setStretch(0, 1)
        self.layout_siteID.setStretch(1, 3)
        self.verticalLayout.addLayout(self.layout_siteID)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_submit = QtWidgets.QPushButton(Dialog)
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout.addWidget(self.btn_submit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Data Center:"))
        self.comboBox.setItemText(0, _translate("Dialog", "Atlanta"))
        self.comboBox.setItemText(1, _translate("Dialog", "Midway"))
        self.label_siteID.setText(_translate("Dialog", "Site ID:"))
        self.btn_submit.setText(_translate("Dialog", "Submit"))
