# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingNDS.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingNDS(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(281, 71)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_nds = QtWidgets.QHBoxLayout()
        self.layout_nds.setSpacing(0)
        self.layout_nds.setObjectName("layout_nds")
        self.label_nds = QtWidgets.QLabel(Dialog)
        self.label_nds.setObjectName("label_nds")
        self.layout_nds.addWidget(self.label_nds)
        self.lineEdit_nds = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_nds.setObjectName("lineEdit_nds")
        self.layout_nds.addWidget(self.lineEdit_nds)
        self.layout_nds.setStretch(0, 1)
        self.layout_nds.setStretch(1, 3)
        self.verticalLayout.addLayout(self.layout_nds)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_submit = QtWidgets.QPushButton(Dialog)
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout.addWidget(self.btn_submit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_nds.setText(_translate("Dialog", "NDS:"))
        self.lineEdit_nds.setInputMask(_translate("Dialog", "000.000.000.000"))
        self.lineEdit_nds.setText(_translate("Dialog", "10.209.25.40"))
        self.btn_submit.setText(_translate("Dialog", "Submit"))
