# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingAALogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingAALoginDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(292, 153)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_aa_login = QtWidgets.QHBoxLayout()
        self.layout_aa_login.setSpacing(0)
        self.layout_aa_login.setObjectName("layout_aa_login")
        self.label_aa_login = QtWidgets.QLabel(Dialog)
        self.label_aa_login.setObjectName("label_aa_login")
        self.layout_aa_login.addWidget(self.label_aa_login)
        self.lineEdit_aa_login = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_aa_login.setInputMask("")
        self.lineEdit_aa_login.setObjectName("lineEdit_aa_login")
        self.layout_aa_login.addWidget(self.lineEdit_aa_login)
        self.layout_aa_login.setStretch(0, 1)
        self.layout_aa_login.setStretch(1, 3)
        self.verticalLayout.addLayout(self.layout_aa_login)
        self.layout_password = QtWidgets.QHBoxLayout()
        self.layout_password.setSpacing(0)
        self.layout_password.setObjectName("layout_password")
        self.label_password = QtWidgets.QLabel(Dialog)
        self.label_password.setObjectName("label_password")
        self.layout_password.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.layout_password.addWidget(self.lineEdit_password)
        self.layout_password.setStretch(0, 1)
        self.layout_password.setStretch(1, 3)
        self.verticalLayout.addLayout(self.layout_password)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btn_submit = QtWidgets.QPushButton(Dialog)
        self.btn_submit.setObjectName("btn_submit")
        self.verticalLayout.addWidget(self.btn_submit)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_aa_login.setText(_translate("Dialog", "AA Login:"))
        self.lineEdit_aa_login.setText(_translate("Dialog", "admin"))
        self.label_password.setText(_translate("Dialog", "Password:"))
        self.lineEdit_password.setText(_translate("Dialog", "S3cur3admin0324"))
        self.checkBox.setText(_translate("Dialog", "Show the Password"))
        self.btn_submit.setText(_translate("Dialog", "Submit"))
